const app = document.querySelector("#app");

const icons = {
  arrow: `<svg viewBox="0 0 20 20" aria-hidden="true"><path d="M4 10h11M11 6l4 4-4 4"/></svg>`,
  shield: `<svg viewBox="0 0 20 20" aria-hidden="true"><path d="M10 2.5 16 5v4.3c0 3.8-2.3 6.5-6 8.2-3.7-1.7-6-4.4-6-8.2V5l6-2.5Z"/><path d="m7.5 10 1.7 1.7 3.6-4"/></svg>`,
  receipt: `<svg viewBox="0 0 20 20" aria-hidden="true"><path d="M5 2.5h10v15l-2.5-1.5-2.5 1.5L7.5 16 5 17.5v-15Z"/><path d="M8 7h4M8 10h4"/></svg>`,
};

function mark(label = "ZERKER") {
  return `<a class="wordmark" href="/reason" aria-label="Zerker Reason home"><span class="mark-glyph"><i></i><i></i></span><b>${label}</b></a>`;
}

function page() {
  return `<main class="zr-shell">
    <nav class="zr-nav">
      <div class="zr-brand">${mark()}<i></i><span>REASON</span></div>
      <div class="zr-preview"><i></i> v0.2</div>
      <div class="zr-nav-links"><a href="https://zerker.ai/">Gateway</a><button type="button" data-zr-scroll="zr-how">How it works</button><button type="button" data-zr-scroll="zr-demo">Live demo</button></div>
    </nav>

    <header class="zr-hero">
      <div class="zr-copy">
        <p>DETERMINISTIC AUTHORIZATION FOR AI AGENTS</p>
        <h1>Every action<br><strong>needs proof.</strong></h1>
        <span>An agent wants to deploy production. Reason checks trusted facts and company rules, then returns an answer anyone can verify.</span>
        <div><button class="zr-primary" type="button" data-zr-scroll="zr-demo">Run the deployment example ${icons.arrow}</button><button type="button" data-zr-scroll="zr-how">See how it works ↓</button></div>
        <small>Local · deterministic · no account · no model required</small>
      </div>
      <div class="zr-kernel" aria-label="Facts, rules, and an action entering the Reason kernel">
        <div class="zr-aura"></div><div class="zr-orbit orbit-one"></div><div class="zr-orbit orbit-two"></div>
        <div class="zr-input input-facts"><small>GOVERNED FACTS</small><b>tests passed · owner approved</b></div>
        <div class="zr-input input-rules"><small>COMPANY RULES</small><b>production_release.v4</b></div>
        <div class="zr-input input-action"><small>EXACT ACTION</small><b>deploy.release(commit_abc)</b></div>
        <div class="zr-core"><div>${mark("REASON")}</div><small>SYMBOLIC KERNEL</small><strong>PROVED</strong><span>sha256:ba4bd9…c6eaf</span></div>
        <div class="zr-certificate">${icons.receipt}<span><small>AUTHORIZATION</small><b>certificate verified</b></span><i></i></div>
      </div>
    </header>

    <section class="zr-demo" id="zr-demo">
      <div class="zr-section-head"><span>01</span><div><p>TRY THE DECISION</p><h2>Should this agent deploy?</h2></div><small>Change the evidence. Only a proven yes can deploy.</small></div>
      <div class="zr-lab">
        <div class="zr-demo-tabs"><button class="active" data-zr-state="authorized"><i></i>All clear</button><button data-zr-state="unknown"><i></i>Approval missing</button><button data-zr-state="denied"><i></i>Release rejected</button><button data-zr-state="conflict"><i></i>Evidence conflicts</button></div>
        <div class="zr-lab-grid">
          <article class="zr-request-card">
            <small>AGENT REQUEST</small><h3>Deploy version 1.4.0 to production.</h3>
            <dl><div><dt>commit</dt><dd>commit_abc</dd></div><div><dt>tool</dt><dd>deploy_release</dd></div><div><dt>requested by</dt><dd>release-agent</dd></div></dl>
            <div class="zr-evidence"><span>TRUSTED EVIDENCE</span><p><i class="ok"></i>Tests passed for this commit</p><p><i class="ok"></i>Security review is current</p><p data-zr-approval><i class="ok"></i>Release owner approved</p></div>
          </article>
          <div class="zr-lab-arrow">→</div>
          <article class="zr-outcome authorized" data-zr-card>
            <div class="zr-outcome-orbit"><span>${icons.shield}</span><i></i><i></i></div>
            <small data-zr-label>AUTHORIZED</small><strong data-zr-verdict>DEPLOY</strong><h3 data-zr-title>Yes. Deploy this commit.</h3><p data-zr-detail>Every required fact is present and trusted.</p><div class="zr-consequence" data-zr-consequence>This exact deployment is eligible for enforcement.</div>
            <dl><div><dt>RESULT</dt><dd data-zr-result>authorized</dd></div><div><dt>EXIT</dt><dd data-zr-exit>0</dd></div><div><dt>REQUEST</dt><dd data-zr-digest>sha256:ffbb68…7c8d5</dd></div></dl>
          </article>
        </div>
        <div class="zr-verification-bar">${icons.shield}<div><b data-zr-foot>Independent verification passed</b><span data-zr-source>Loaded from a certificate generated by Zerker Reason</span></div><a data-zr-certificate-link href="/reason/data/reason/authorized-certificate.json" download>Download certificate ${icons.arrow}</a></div>
        <details class="zr-dev-proof"><summary>View developer proof</summary><div class="zr-terminal"><div><i></i><i></i><i></i><span>reason authorize</span></div><pre data-zr-command><em>$</em> reason authorize data/reason/authorized-request.json

<span>AUTHORIZED</span>  action_deploy_140
            deploy_release(commit_abc, production)
            proof sha256:ba4bd9…c6eaf

<small>Exit 0 · certificate independently verified</small></pre></div></details>
      </div>
    </section>

    <section class="zr-how" id="zr-how">
      <div class="zr-section-head"><span>02</span><div><p>THE AUTHORIZATION PATH</p><h2>The model proposes. The kernel verifies.</h2></div></div>
      <div class="zr-path"><article><small>01 · PROPOSE</small><h3>Agent action</h3><p>Mission, exact tool, normalized arguments, effects, and evaluation time.</p></article><i>→</i><article><small>02 · ADMIT</small><h3>Governed facts</h3><p>Only evidence from an accepted authority enters the reasoning snapshot.</p></article><i>→</i><article><small>03 · DERIVE</small><h3>Symbolic proof</h3><p>Typed rules preserve unknown, negative, and contradictory support.</p></article><i>→</i><article><small>04 · VERIFY</small><h3>Replayable certificate</h3><p>An independent checker verifies every node without trusting the solver.</p></article></div>
    </section>

    <section class="zr-truth">
      <div><p>FOUR-STATE TRUTH</p><h2>Unknown is not false.<br>Conflict is not permission.</h2></div>
      <div class="zr-truth-grid"><article class="proved"><span>01</span><b>PROVED</b><p>Required support exists.</p><code>exit 0</code></article><article><span>02</span><b>UNKNOWN</b><p>Evidence is missing.</p><code>exit 2</code></article><article class="denied"><span>03</span><b>DISPROVED</b><p>Negative support exists.</p><code>exit 3</code></article><article class="conflict"><span>04</span><b>INCONSISTENT</b><p>Both sides have support.</p><code>exit 4</code></article></div>
    </section>

    <section class="zr-certificate-section">
      <div class="zr-section-head"><span>03</span><div><p>BOUND TO THE EXACT REQUEST</p><h2>A certificate cannot drift.</h2></div><small>Change one argument and verification fails.</small></div>
      <div class="zr-bindings"><span>MISSION</span><i></i><span>TOOL</span><i></i><span>ARGUMENTS</span><i></i><span>EFFECTS</span><i></i><span>POLICY</span><i></i><span>EVIDENCE</span><i></i><span>TIME</span></div>
      <pre data-zr-json>{
  <b>"schema"</b>: <em>"zerker.reason.authorization.v1"</em>,
  <b>"status"</b>: <em>"authorized"</em>,
  <b>"action"</b>: { <b>"tool"</b>: <em>"deploy_release"</em>, <b>"commit"</b>: <em>"commit_abc"</em> },
  <b>"request_digest"</b>: <em>"sha256:ffbb682242b1..."</em>,
  <b>"proof_digest"</b>: <em>"sha256:ba4bd960b803..."</em>
}</pre>
      <div class="zr-json-actions"><a data-zr-request-link href="/reason/data/reason/authorized-request.json" download>Download request ${icons.arrow}</a><a data-zr-verification-link href="/reason/data/reason/authorized-verification.json" download>Download verification ${icons.arrow}</a></div>
    </section>

    <section class="zr-stack">
      <div><p>ONE JOB PER BOUNDARY</p><h2>Reason proves.<br>The stack does the rest.</h2></div>
      <div><article><span>ZMEM</span><b>Supplies governed premises</b><small>GOVERNED EXPORT MERGED</small></article><article class="current"><span>REASON</span><b>Derives and verifies authorization</b><small>WORKING STANDALONE</small></article><article><span>GATEWAY</span><b>Enforces the exact MCP call</b><small>INTEGRATION MERGED</small></article><article><span>RAKHSHAK</span><b>Binds process and destination</b><small>INTEGRATION MERGED</small></article><article><span>TREESHIP</span><b>Preserves verified decisions</b><small>VERIFY-THEN-SIGN PR OPEN</small></article></div>
    </section>

    <section class="zr-start"><div><p>RUN IT LOCALLY</p><h2>Proof in two commands.</h2><span>No daemon, network, account, wall clock, or LLM.</span></div><pre><i>$</i> reason authorize deploy.json \
    --certificate-out authorization.json
<i>$</i> reason verify-authorization \
    deploy.json authorization.json
<span>✓ VERIFIED_AUTHORIZATION</span></pre></section>
    <footer class="zr-footer"><div>${mark()}<i></i><span>REASON</span></div><p>Apache 2.0 · deterministic · local first</p><a href="https://zerker.ai/">Explore Zerker Gateway →</a></footer>
  </main>`;
}

const scenarios = {
  authorized: { label: "AUTHORIZED", verdict: "DEPLOY", title: "Yes. Deploy this commit.", detail: "Every required fact is present and trusted.", consequence: "This exact deployment is eligible for enforcement.", approval: "Release owner approved", evidenceTone: "ok", exit: "0", tone: "authorized" },
  unknown: { label: "BLOCKED", verdict: "WAIT", title: "Not yet. Approval is missing.", detail: "Tests passed, but no trusted release-owner approval exists.", consequence: "The deployment stays blocked until an authorized owner approves it.", approval: "Release approval is missing", evidenceTone: "missing", exit: "2", tone: "unknown" },
  denied: { label: "BLOCKED", verdict: "STOP", title: "No. This release was rejected.", detail: "A trusted release authority explicitly rejected this deployment.", consequence: "The deployment tool will not run.", approval: "Release owner rejected", evidenceTone: "denied", exit: "3", tone: "denied" },
  conflict: { label: "BLOCKED", verdict: "STOP", title: "The evidence conflicts.", detail: "Trusted approval and trusted rejection both exist.", consequence: "The deployment stays blocked until the conflict is resolved.", approval: "Approved and rejected", evidenceTone: "conflict", exit: "4", tone: "conflict" },
};

const cache = new Map();
const shortDigest = value => value ? `${value.slice(0, 20)}…${value.slice(-6)}` : "none";
const escapeHtml = value => String(value).replace(/[&<>"']/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]);

async function fetchJsonWithDigest(url, expectedDigest) {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${url} unavailable`);
  const bytes = await response.arrayBuffer();
  const digestBytes = await crypto.subtle.digest("SHA-256", bytes);
  const digest = `sha256:${[...new Uint8Array(digestBytes)].map(byte => byte.toString(16).padStart(2, "0")).join("")}`;
  if (digest !== expectedDigest) throw new Error(`${url} does not match fixture manifest`);
  return JSON.parse(new TextDecoder().decode(bytes));
}

async function loadScenario(key) {
  const scenario = scenarios[key];
  if (!scenario) return;
  document.querySelectorAll("[data-zr-state]").forEach(element => element.classList.toggle("active", element.dataset.zrState === key));
  const card = document.querySelector("[data-zr-card]");
  if (card) card.className = `zr-outcome ${scenario.tone}`;
  try {
    let data = cache.get(key);
    if (!data) {
      const base = `/reason/data/reason/${key}`;
      const manifestResponse = await fetch("/reason/data/reason/manifest.json");
      if (!manifestResponse.ok) throw new Error("fixture manifest unavailable");
      const manifest = await manifestResponse.json();
      const expected = manifest.scenarios?.[key]?.artifacts;
      if (!expected) throw new Error(`fixture manifest has no ${key} scenario`);
      const [certificate, verification, request] = await Promise.all([
        fetchJsonWithDigest(`${base}-certificate.json`, expected.certificate),
        fetchJsonWithDigest(`${base}-verification.json`, expected.verification),
        fetchJsonWithDigest(`${base}-request.json`, expected.request),
      ]);
      data = { certificate, verification, request, manifest };
      cache.set(key, data);
    }
    if (!document.querySelector(`[data-zr-state='${key}'].active`)) return;
    const { certificate, verification, manifest } = data;
    const proofDigest = certificate.reasoning?.proof?.digest;
    const disproofDigest = certificate.reasoning?.disproof?.digest;
    const evidenceDigest = proofDigest || disproofDigest || verification.reasoning_result_digest;
    const issue = certificate.issues?.[0];
    const conflict = certificate.reasoning?.conflict;
    const values = {
      "[data-zr-label]": scenario.label,
      "[data-zr-verdict]": scenario.verdict,
      "[data-zr-title]": scenario.title,
      "[data-zr-detail]": scenario.detail,
      "[data-zr-consequence]": scenario.consequence,
      "[data-zr-result]": certificate.status,
      "[data-zr-exit]": scenario.exit,
      "[data-zr-foot]": verification.status === "verified" ? `Certificate verified · ${verification.authorization_status}` : "Verification failed",
      "[data-zr-digest]": shortDigest(certificate.request_digest),
      "[data-zr-source]": `${manifest.generator} · ${verification.status} · fetched bytes match fixture SHA-256 manifest`,
    };
    Object.entries(values).forEach(([selector, value]) => {
      const element = document.querySelector(selector);
      if (element) element.textContent = value;
    });
    const approval = document.querySelector("[data-zr-approval]");
    if (approval) approval.innerHTML = `<i class="${scenario.evidenceTone}"></i>${escapeHtml(scenario.approval)}`;
    const proofLine = conflict ? `proof ${shortDigest(proofDigest)}\ndisproof ${shortDigest(disproofDigest)}` : `${proofDigest ? "proof" : disproofDigest ? "disproof" : "result"} ${shortDigest(evidenceDigest)}`;
    const issueLine = issue ? `\n${issue.code}: ${issue.atom ? `${issue.atom.predicate}(${issue.atom.arguments.join(", ")})` : issue.message}` : "";
    const command = document.querySelector("[data-zr-command]");
    if (command) command.innerHTML = `<em>$</em> reason authorize data/reason/${key}-request.json\n\n<span>${escapeHtml(scenario.label)}</span>  ${escapeHtml(certificate.action.id)}\n            ${escapeHtml(certificate.action.tool)}(${escapeHtml(Object.values(certificate.action.arguments).join(", "))})\n            ${escapeHtml(proofLine)}${escapeHtml(issueLine)}\n\n<small>Exit ${scenario.exit} · certificate independently ${escapeHtml(verification.status)}</small>`;
    const certificateView = document.querySelector("[data-zr-json]");
    if (certificateView) certificateView.textContent = JSON.stringify({
      schema: certificate.schema,
      status: certificate.status,
      action: certificate.action,
      request_digest: certificate.request_digest,
      reasoning: {
        status: certificate.reasoning.status,
        program_digest: certificate.reasoning.program_digest,
        proof_digest: proofDigest || null,
        disproof_digest: disproofDigest || null,
      },
      verification,
    }, null, 2);
    const links = {
      "[data-zr-certificate-link]": `/reason/data/reason/${key}-certificate.json`,
      "[data-zr-request-link]": `/reason/data/reason/${key}-request.json`,
      "[data-zr-verification-link]": `/reason/data/reason/${key}-verification.json`,
    };
    Object.entries(links).forEach(([selector, href]) => document.querySelector(selector)?.setAttribute("href", href));
  } catch (error) {
    const source = document.querySelector("[data-zr-source]");
    if (source) source.textContent = `Could not load certificate: ${error.message}`;
  }
}

app.innerHTML = page();
document.querySelectorAll("[data-zr-scroll]").forEach(button => button.addEventListener("click", () => document.getElementById(button.dataset.zrScroll)?.scrollIntoView()));
document.querySelectorAll("[data-zr-state]").forEach(button => button.addEventListener("click", () => loadScenario(button.dataset.zrState)));
loadScenario("authorized");
